name: sparkle-note-frontend-deploy

on:
  push:
    branches: [ "dev" , "main"]  # 백엔드와 동일하게 dev, main 브랜치에서 동작

jobs:
  deploy:
    name: react frontend ci-cd
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. npm 의존성 설치 및 빌드
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build

      # 4. 빌드된 파일을 EC2로 전송
      - name: Upload build files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/var/www/sparklenote"
          strip_components: 1

      # 5. Nginx 재시작
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Restarting Nginx..."
            sudo systemctl restart nginx